#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p26 b 179 26"
export BOOTREC_CACHE="/dev/block/mmcblk0p26"
export BOOTREC_DATA_NODE="/dev/block/mmcblk0p27 b 179 27"
export BOOTREC_DATA="/dev/block/mmcblk0p27"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p21 b 179 21"
export BOOTREC_FOTA="/dev/block/mmcblk0p21"
export BOOTREC_EVENT_NODE="/dev/input/event2 c 13 66"
export BOOTREC_EVENT="/dev/input/event2"
export BOOTREC_LED_RED="/sys/class/leds/led:rgb_red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/led:rgb_green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/led:rgb_blue/brightness"
export BOOTREC_VIBRATOR="/sys/class/timed_output/vibrator/enable"
